# Based on https://github.com/edzer/sfr/blob/master/.travis.yml
# See also https://docs.travis-ci.com/user/languages/r and https://github.com/hadley/devtools/blob/master/.travis.yml
# For a potential alternative configuration see https://github.com/metacran/r-builder

language: r
cache: packages
sudo: required
dist: trusty

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev

warnings_are_errors: true

r_packages:
  - rgdal
  - roxygen2
  - covr

repos:
  CRAN: https://cloud.r-project.org
  ropensci: http://packages.ropensci.org

after_success:
#  - Rscript -e 'covr::codecov()'
  - Rscript -e 'lintr::lint_package()'
  - echo $TRAVIS_R_VERSION
  - echo $TRAVIS_OS_NAME
