# Based on https://docs.travis-ci.com/user/languages/r and https://github.com/hadley/devtools/blob/master/.travis.yml
# For a potential alternative configuration see https://github.com/metacran/r-builder

language: r
cache: packages

# use explicit matrix below to configure specific build args
#r:
#  - oldrel
#  - release
#  - devel
#os:
#- linux
#- osx

# based on https://github.com/jeroenooms/curl/blob/master/.travis.yml and
# https://github.com/IRkernel/IRkernel/blob/master/.travis.yml and
# https://github.com/jonkeane/mocapGrip/blob/master/.travis.yml
matrix:
  include:
    - os: linux
      r: release
    - os: linux
      r: devel
    - os: linux
      r: oldrel
      r_build_args: '--no-build-vignettes'
      r_check_args: '--ignore-vignettes --no-examples'
    - os: linux
      dist: trusty
      r: release
      env: R_CODECOV=true
    - os: osx
      osx_image: xcode8
      #before_install:
      #  - brew install curl
      latex: false
      r_build_args: '--no-build-vignettes'
      r_check_args: '--ignore-vignettes --no-examples'
    - os: osx
      osx_image: xcode7.3
      latex: false
      r_build_args: '--no-build-vignettes'
      r_check_args: '--ignore-vignettes --no-examples'
    - os: osx
      osx_image: beta-xcode6.1
      disable_homebrew: true

warnings_are_errors: true

r_packages:
  - roxygen2
  - covr
  - rgdal

repos:
  CRAN: https://cloud.r-project.org
  ropensci: http://packages.ropensci.org

before_script:
  - git config --global user.name "travis"
  - git config --global user.email "travis@example.org"

after_success:
#  - Rscript -e 'covr::codecov()'
  - echo $TRAVIS_R_VERSION
  - echo $TRAVIS_OS_NAME
